import io
import re
from datetime import date
from xml.sax.saxutils import escape as xml_escape
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, PageBreak, HRFlowable,
)
from .. import models
from ..database import get_db
from ..auth import require_any
from ..engine.mapper import compute_results, compute_summary

router = APIRouter(prefix="/assessments", tags=["export"])


def _safe_filename(name: str) -> str:
    """Strip characters that are unsafe in Content-Disposition filenames."""
    return re.sub(r'[^\w\-.]', '_', name)


# ── Colours ───────────────────────────────────────────────────────────────────
C_COVERED     = colors.HexColor("#00B050")
C_PARTIAL     = colors.HexColor("#FFC000")
C_NOT_COVERED = colors.HexColor("#E02020")
C_HEADER_BG   = colors.HexColor("#1E293B")   # slate-800
C_ACCENT      = colors.HexColor("#10B981")   # emerald-500
C_LIGHT_GRAY  = colors.HexColor("#F8FAFC")
C_MID_GRAY    = colors.HexColor("#E2E8F0")
C_TEXT        = colors.HexColor("#1E293B")

STATUS_COLOR = {
    "covered":     C_COVERED,
    "partial":     C_PARTIAL,
    "not_covered": C_NOT_COVERED,
}
STATUS_LABEL = {
    "covered":     "Covered",
    "partial":     "Partial",
    "not_covered": "Not Covered",
}


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", parent=base["Title"],
            fontSize=28, textColor=C_TEXT, spaceAfter=4, alignment=TA_CENTER),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"],
            fontSize=13, textColor=colors.HexColor("#64748B"),
            spaceAfter=2, alignment=TA_CENTER),
        "section": ParagraphStyle("section", parent=base["Heading2"],
            fontSize=13, textColor=C_HEADER_BG,
            spaceBefore=14, spaceAfter=6, borderPad=(0,0,2,0)),
        "body": ParagraphStyle("body", parent=base["Normal"],
            fontSize=9, textColor=C_TEXT, leading=12),
        "small": ParagraphStyle("small", parent=base["Normal"],
            fontSize=8, textColor=colors.HexColor("#64748B"), leading=10),
        "cell": ParagraphStyle("cell", parent=base["Normal"],
            fontSize=8, textColor=C_TEXT, leading=11, wordWrap="CJK"),
        "cell_dim": ParagraphStyle("cell_dim", parent=base["Normal"],
            fontSize=8, textColor=colors.HexColor("#94A3B8"), leading=11),
    }


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = letter
    # Top bar
    canvas.setFillColor(C_HEADER_BG)
    canvas.rect(0, h - 28, w, 28, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(0.5 * inch, h - 18, "CAAMS — Compliance and Auditing Made Simple")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(w - 0.5 * inch, h - 18, f"CONFIDENTIAL — {date.today().strftime('%B %d, %Y')}")
    # Footer
    canvas.setFillColor(colors.HexColor("#94A3B8"))
    canvas.setFont("Helvetica", 7)
    canvas.drawString(0.5 * inch, 0.3 * inch, "Generated by CAAMS")
    canvas.drawRightString(w - 0.5 * inch, 0.3 * inch, f"Page {doc.page}")
    canvas.restoreState()


def _summary_table(summary: dict, st: dict):
    labels = [
        ("Total Controls", str(summary["total"]),   C_HEADER_BG),
        ("Covered",        str(summary["covered"]),  C_COVERED),
        ("Partial",        str(summary["partial"]),  C_PARTIAL),
        ("Not Covered",    str(summary["not_covered"]), C_NOT_COVERED),
        ("Coverage Score", f"{summary['coverage_pct']}%", C_ACCENT),
    ]
    data = [[
        Paragraph(f'<font color="white"><b>{v}</b><br/><font size="8">{lbl}</font></font>', st["subtitle"])
        for lbl, v, _ in labels
    ]]
    t = Table(data, colWidths=[1.35 * inch] * 5, rowHeights=[0.7 * inch])
    t.setStyle(TableStyle([
        *[("BACKGROUND", (i, 0), (i, 0), col) for i, (_, _, col) in enumerate(labels)],
        ("ALIGN",      (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.transparent]),
        ("ROUNDEDCORNERS", [4]),
        ("BOX",        (0, 0), (-1, -1), 0, colors.transparent),
        ("INNERGRID",  (0, 0), (-1, -1), 0.5, colors.white),
    ]))
    return t


def _coverage_report_table(results: list, st: dict):
    col_widths = [0.65*inch, 1.75*inch, 0.75*inch, 0.9*inch, 0.9*inch, 0.9*inch, 1.35*inch, 1.15*inch]
    headers = ["Control", "Title", "Status", "Owner", "Team", "Evidence Owner", "Covered By", "Missing Tags"]

    def hcell(txt):
        return Paragraph(f'<font color="white"><b>{txt}</b></font>', st["small"])

    rows = [[hcell(h) for h in headers]]
    style_cmds = [
        ("BACKGROUND",  (0, 0), (-1, 0), C_HEADER_BG),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, C_LIGHT_GRAY]),
        ("ALIGN",       (0, 0), (-1, -1), "LEFT"),
        ("VALIGN",      (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE",    (0, 0), (-1, -1), 8),
        ("TOPPADDING",  (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING",(0, 0), (-1, -1), 4),
        ("GRID",        (0, 0), (-1, -1), 0.3, C_MID_GRAY),
    ]

    for i, r in enumerate(results, 1):
        sc = STATUS_COLOR.get(r["status"], colors.gray)
        sl = STATUS_LABEL.get(r["status"], r["status"])
        status_cell = Paragraph(
            f'<font color="white"><b>{sl}</b></font>',
            ParagraphStyle("sc", parent=st["cell"], backColor=sc, textColor=colors.white,
                           borderPad=2, leading=10)
        )
        rows.append([
            Paragraph(xml_escape(r["control_id"]), st["cell"]),
            Paragraph(xml_escape(r["title"]), st["cell"]),
            status_cell,
            Paragraph(xml_escape(r.get("owner") or "—"), st["cell"] if r.get("owner") else st["cell_dim"]),
            Paragraph(xml_escape(r.get("team") or "—"), st["cell"] if r.get("team") else st["cell_dim"]),
            Paragraph(xml_escape(r.get("evidence_owner") or "—"), st["cell"] if r.get("evidence_owner") else st["cell_dim"]),
            Paragraph(xml_escape(", ".join(r["contributing_tools"])) or "—", st["cell"]),
            Paragraph(xml_escape(", ".join(r["missing_tags"])) or "—",
                      ParagraphStyle("mt", parent=st["cell"], textColor=C_NOT_COVERED if r["missing_tags"] else colors.HexColor("#94A3B8"))),
        ])
        style_cmds.append(("BACKGROUND", (2, i), (2, i), sc))

    t = Table(rows, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle(style_cmds))
    return t


def _evidence_checklist_table(results: list, st: dict):
    col_widths = [0.65*inch, 1.6*inch, 2.2*inch, 0.75*inch, 0.95*inch, 0.95*inch, 0.95*inch, 0.6*inch]
    headers = ["Control", "Title", "Evidence Item", "Status", "Owner", "Team", "Evidence Owner", "Notes"]

    def hcell(txt):
        return Paragraph(f'<font color="white"><b>{txt}</b></font>', st["small"])

    rows = [[hcell(h) for h in headers]]
    style_cmds = [
        ("BACKGROUND",  (0, 0), (-1, 0), C_HEADER_BG),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, C_LIGHT_GRAY]),
        ("ALIGN",       (0, 0), (-1, -1), "LEFT"),
        ("VALIGN",      (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE",    (0, 0), (-1, -1), 7.5),
        ("TOPPADDING",  (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING",(0, 0), (-1, -1), 4),
        ("GRID",        (0, 0), (-1, -1), 0.3, C_MID_GRAY),
    ]

    for i, r in enumerate(results):
        sc = STATUS_COLOR.get(r["status"], colors.gray)
        sl = STATUS_LABEL.get(r["status"], r["status"])
        for evidence_item in r["evidence"]:
            rows.append([
                Paragraph(xml_escape(r["control_id"]), st["cell"]),
                Paragraph(xml_escape(r["title"]), st["cell"]),
                Paragraph(xml_escape(evidence_item), st["cell"]),
                Paragraph(f'<font color="white"><b>{sl}</b></font>',
                          ParagraphStyle("sc2", parent=st["cell"], backColor=sc, textColor=colors.white, leading=10)),
                Paragraph(xml_escape(r.get("owner") or ""), st["cell"]),
                Paragraph(xml_escape(r.get("team") or ""), st["cell"]),
                Paragraph(xml_escape(r.get("evidence_owner") or ""), st["cell"]),
                Paragraph("", st["cell"]),  # Notes — auditor fills in
            ])

    t = Table(rows, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle(style_cmds))
    return t


@router.get("/{assessment_id}/export/pdf")
def export_assessment_pdf(assessment_id: int, db: Session = Depends(get_db), _=Depends(require_any)):
    assessment = db.query(models.Assessment).filter(
        models.Assessment.id == assessment_id
    ).first()
    if not assessment:
        raise HTTPException(status_code=404, detail="Assessment not found")

    results = compute_results(assessment, db)
    summary = compute_summary(results)
    st = _styles()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
        topMargin=0.55 * inch,
        bottomMargin=0.5 * inch,
    )

    story = []

    # ── Cover page ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 0.6 * inch))
    story.append(Paragraph("CAAMS", ParagraphStyle("brand", parent=st["title"],
        fontSize=11, textColor=C_ACCENT, spaceAfter=2, alignment=TA_CENTER)))
    story.append(Paragraph("Compliance Coverage Report", st["title"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(HRFlowable(width="80%", thickness=1.5, color=C_ACCENT,
                             spaceAfter=10, spaceBefore=4, hAlign="CENTER"))
    story.append(Paragraph(xml_escape(assessment.name), ParagraphStyle("assname", parent=st["subtitle"],
        fontSize=16, textColor=C_TEXT, spaceAfter=4, alignment=TA_CENTER)))
    story.append(Paragraph(
        f"{xml_escape(assessment.framework.name)} &nbsp;·&nbsp; {xml_escape(assessment.framework.version)}",
        st["subtitle"],
    ))
    story.append(Paragraph(date.today().strftime("%B %d, %Y"), st["subtitle"]))
    story.append(Spacer(1, 0.4 * inch))
    story.append(_summary_table(summary, st))
    story.append(Spacer(1, 0.25 * inch))

    # Coverage bar (drawn as a simple one- or two-cell table)
    pct = summary["coverage_pct"]
    bar_w = 6.75 * inch
    covered_w = bar_w * pct / 100
    gap_w = bar_w - covered_w
    if gap_w <= 0:
        bar = Table([[""]], colWidths=[bar_w], rowHeights=[14])
        bar.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, 0), C_ACCENT),
            ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
        ]))
    else:
        bar = Table([["", ""]], colWidths=[covered_w, gap_w], rowHeights=[14])
        bar.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, 0), C_ACCENT),
            ("BACKGROUND", (1, 0), (1, 0), C_MID_GRAY),
            ("BOX", (0, 0), (-1, -1), 0, colors.transparent),
        ]))
    story.append(bar)
    story.append(Paragraph(
        f"Coverage score: <b>{pct}%</b>  (covered + 0.5 × partial)",
        ParagraphStyle("barlabel", parent=st["small"], alignment=TA_CENTER, spaceAfter=0, spaceBefore=4),
    ))

    story.append(PageBreak())

    # ── Coverage Report ───────────────────────────────────────────────────────
    story.append(Paragraph("Coverage Report", st["section"]))
    story.append(Spacer(1, 4))
    story.append(_coverage_report_table(results, st))

    story.append(PageBreak())

    # ── Evidence Checklist ────────────────────────────────────────────────────
    story.append(Paragraph("Evidence Checklist", st["section"]))
    story.append(Paragraph(
        "Use this checklist to track evidence collection. Fill in the Notes column as artifacts are gathered.",
        st["small"],
    ))
    story.append(Spacer(1, 6))
    story.append(_evidence_checklist_table(results, st))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)

    filename = f"assessment_{assessment_id}_{_safe_filename(assessment.name)}_coverage.pdf"
    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
